kind: pipeline
name: default

volumes:
  - name: out
    temp: {}

steps:
  - name: build
    image: archlinux:latest

    commands:
      - yes | pacman -Syu
      - yes | pacman -S gcc
      - yes | pacman -S pkgconf
      - yes | pacman -S glfw-x11
      - yes | pacman -S go
      - go build ./...
      - go test -cover ./...
      - mkdir /out/linux_x64
      - go build -o /out/linux-x64/tob-cob

    volumes:
      - name: out
        path: /out

  - name: deploy
    image: archlinux:latest

    commands:
      - yes | pacman -Syu
      - yes | pacman -S curl
      - yes | pacman -S unzip
      - mkdir -p ~/.config/itch
      - echo $BUTLER_API_KEY > ~/.config/itch/butler_creds
      - wc ~/.config/itch/butler_creds
      - curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/15.17.0/archive/default
      - unzip butler.zip
      - chmod +x butler
      - ./butler -V
      - ./butler push /out/linux-x64 szabba/tears-of-butterflies-colors-of-blood:linux-x64

    volumes:
      - name: out
        path: /out

    environment:
      BUTLER_API_KEY:
        from_secret: BUTLER_API_KEY
