kind: pipeline
name: default

steps:
  - name: build
    image: archlinux:latest

    commands:
      - yes | pacman -Syu
      - yes | pacman -S gcc
      - yes | pacman -S pkgconf
      - yes | pacman -S glfw-x11
      - yes | pacman -S go
      - go build $BUILD_FLAGS ./...
      - go test $BUILD_FLAGS -cover ./...
      - mkdir /out/linux-x64
      - go build $BUILD_FLAGS -o /out/linux-x64/tob-cob
      - mkdir /out/linux-x64/assets
      - cp -r ./assets/* /out/linux-x64/assets

    environment:
      BUILD_FLAGS: -trimpath

    volumes:
      - name: out
        path: /out

  - name: deploy
    image: archlinux:latest

    commands:
      - yes | pacman -Syu
      - yes | pacman -S curl
      - yes | pacman -S unzip
      - mkdir -p ~/.config/itch
      - echo $BUTLER_API_KEY > ~/.config/itch/butler_creds
      - wc ~/.config/itch/butler_creds
      - curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/15.17.0/archive/default
      - unzip butler.zip
      - chmod +x butler
      - ./butler -V
      - ./butler push /out/linux-x64 szabba/tears-of-butterflies-colors-of-blood:linux-x64

    environment:
      BUTLER_API_KEY:
        from_secret: BUTLER_API_KEY

    volumes:
      - name: out
        path: /out

volumes:
  - name: out
    temp: {}
