kind: pipeline
name: default

steps:
  - name: build
    image: archlinux:latest
    commands:
      - yes | pacman -Syu
      - yes | pacman -S go
      - yes | pacman -S glfw-x11
      - go build -x ./...
      - go test -cover ./...
