kind: pipeline
name: default

steps:
  - name: build
    image: archlinux:latest
    commands:
      - yes | pacman -Syu
      - yes | pacman -S gcc
      - yes | pacman -S pkgconf
      - yes | pacman -S glfw-x11
      - yes | pacman -S go
      - go build ./...
      - go test -cover ./...
      - go build ./tob-cob
  - name: deploy
    image: archlinux:latest
    commands:
      - echo $BUTLER_API_KEY > ~/.config/itch/butler_creds
      - wc ~/.config/itch/butler_creds
    environment:
      BUTLER_API_KEY:
        from_secret: BUTLER_API_KEY
