kind: pipeline
name: default

steps:
  - name: build
    image: archlinux:latest
    commands:
      - yes | pacman -Syu
      - yes | pacman -S base-devel
      - yes | pacman -S glfw-x11
      - yes | pacman -S go
      - go build ./...
      - go test -cover ./...
